# It contains all the configs required in the project

artifacts:
  artifacts_dir: artifacts
  cache_dir: cache_dir

dataset:
  name: xtreme
  subset: PAN-X.en

source_download_dirs:
  - path_to_data_1
